name: flutter_template_for_hackathon
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  hooks_riverpod: ^2.4.1
  fl_chart: ^0.63.0
  shared_preferences: ^2.2.1
  sensors_plus: ^3.0.3
  flutter_hooks: ^0.20.1
  riverpod_annotation: ^2.1.6
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.4.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.3
flutter:
  uses-material-design: true
  assets:
    - assets/
